### PR TITLE
Added Discord login and SomToday tables

### PR DESCRIPTION
**Pull request by Underlyingglitch**
This PR includes:
- Some minor bug fixes.
- A new profile page
- Unnecessary tables got removed from the DB
- New logo
- Profile page is now accessible by clicking on your name in the top right corner. The link in the sidebar got removed to make space for future functionalities
- Discord authentication now fully functional
- Removed the TestController as it should never have been commited anyways. (whoops)

### CODE REVIEW

**Review by 25huizengek1 — CHANGES_REQUESTED** [review]
Why have a DiscordProfile model and store the Discord token in the user itself? That doesn't make sense.

**Comment by Underlyingglitch** [comment]
> Why have a DiscordProfile model and store the Discord token in the user itself? That doesn't make sense.

That's because the Discord token will be different every time a user logs in. This is usually stored in the User object and not in the Profile. The Profile only contains the profile data for the user. All authentication methods are stored in the User object.

**Comment by 25huizengek1** [comment]
But the token belongs to the Discord user? I still don't get it.

**Comment by Underlyingglitch** [comment]
> But the token belongs to the Discord user? I still don't get it.

True, however the token isn't profile data. It is only used to authenticate the user at this moment. I have followed documentation:
https://laravel.com/docs/9.x/socialite#authentication-and-storage

**Review by 25huizengek1 — APPROVED** [review]
Alright, imma approve then, but if this causes errors in the future don't say I didn't warn you! :joy:

**Comment by Underlyingglitch** [comment]
I will promise to quietly fix those possible errors then!😂

**Comment by 25huizengek1** [comment]
Promise { <pending> }

**Pull request merged**
